/*
 * File: app/view/ExtlinerMainPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ExtlinerMainPanel', {
    extend: 'Ext.panel.Panel',

    height: 600,
    width: 800,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: 'Extliner',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    flex: 0.3,
                    autoScroll: true,
                    title: 'Topics',
                    store: 'ExtlinerTreeStore',
                    viewConfig: {

                    },
                    tools: [
                        {
                            xtype: 'tool',
                            type: 'plus'
                        },
                        {
                            xtype: 'tool',
                            type: 'minus'
                        },
                        {
                            xtype: 'tool',
                            type: 'save'
                        }
                    ]
                },
                {
                    xtype: 'htmleditor',
                    flex: 1,
                    style: 'background-color: white;'
                }
            ]
        });

        me.callParent(arguments);
    }

});